<?php
return [
    'index.php' => [AuthController::class, 'home'],
    '' => [AuthController::class, 'home'],
    'login.php' => [AuthController::class, 'login'],
    'logout.php' => [AuthController::class, 'logout'],
    'dashboard.php' => [DashboardController::class, 'index'],
    'rooms.php' => [RoomController::class, 'index'],
    'room_form.php' => [RoomController::class, 'form'],
    'room_delete.php' => [RoomController::class, 'delete'],
    'reservations.php' => [ReservationController::class, 'adminIndex'],
    'reservation_form.php' => [ReservationController::class, 'form'],
    'reservation_action.php' => [ReservationController::class, 'action'],
    'reservation_cancel.php' => [ReservationController::class, 'cancel'],
    'document.php' => [ReservationController::class, 'document'],
    'my_reservations.php' => [ReservationController::class, 'mine'],
    'history.php' => [ReservationController::class, 'history'],
    'calendar.php' => [CalendarController::class, 'index'],
    'reports.php' => [ReportController::class, 'index'],
    'profile.php' => [ProfileController::class, 'index'],
    'users.php' => [UserController::class, 'index'],
    'user_form.php' => [UserController::class, 'form'],
    'user_delete.php' => [UserController::class, 'delete'],
];
